### ISSUE TITLE
Avoid reports from CPAN testers failing to load Tk

### ISSUE THREAD

**Issue by chrstphrchvz** [chrstphrchvz/tkx#2]
Many spurious FAIL reports from CPAN testers are due to failure during Tkx doing `package require Tk`, e.g. `can't find package Tk` or `no display name and no $DISPLAY environment variable` or `version conflict for package "Tcl"`.

I will likely address this by having Makefile.PL `exit 0` without emitting a Makefile unless it can successfully do `package require Tk`, as done by Tcl::Tk and Tcl::pTk. However I would do this check via Tcl.pm rather than find/ask for tclsh. Passing `--no-test-for-tk` would skip the check (useful for environments needing to build modules headlessly).

**Comment by eserte** [comment]
Maybe you can apply the same hack like Perl/Tk: if there's no DISPLAY available, then the test suite is largely skipped.
(Technically there's no requirement to have a working DISPLAY while building a package --- it should be just there when using the module)

**Comment by chrstphrchvz** [comment]
Checking for DISPLAY would only check for headlessness, which may be enough for Perl/Tk since it bundles its dependencies, while Tkx and other wrappers still need to check for separately-installed Tcl/Tk.

**Comment by chrstphrchvz** [comment]
Regarding package version conflict issue: I'm not sure Tkx can/should do anything about it. I'm not aware if it would help if Tkx tried the approach in Tcl::Tk/Tcl::pTk to first try loading Tk with the same version as Tcl (which I predict will complain when Tk 8.7 needs to be run on Tcl 9: vadrer/perl-tcl-tk#36).
